name: take
description: A new Flutter project.
publish_to: 'none'
version: 3.3.0+13

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_app_check: ^0.1.1+8
  firebase_core:
  firebase_analytics:
  firebase_auth:
  cloud_firestore:
  google_maps_flutter_web: ^0.4.0+3
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  filter_list: ^1.0.2
  full_screen_image: ^1.0.2
  csc_picker: ^0.2.6
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  flutter_styled_toast: ^2.1.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  firebase_storage:
  font_awesome_flutter: ^10.2.1
  internet_connection_checker: ^1.0.0+1
  google_maps_flutter: ^2.2.2
  flutter_image_compress: ^1.1.3
  flutter_html: ^2.2.1
  url_launcher: ^6.1.7
  flutter_riverpod: ^2.1.2
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  spell_checker: ^0.1.2+3
  shimmer: ^2.0.0
  georange: ^1.0.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^9.1.4
  awesome_notifications: ^0.7.4+1
  change_app_package_name: ^1.1.0
  dropdown_search: ^5.0.5
  easy_debounce: ^2.0.3
  flutter_animate: 1.0.0
  page_transition: ^2.0.9

  go_router: 3.1.0
  auto_size_text: ^3.0.0
  mime_type: ^1.0.0
  file_picker: ^5.2.5
  from_css_color: ^2.0.0
  json_path: ^0.4.2
  timeago: ^3.3.0
  image: ^3.1.3
  built_value: ^8.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  snippet_coder_utils: ^1.0.9
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
  
